apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.graphql.appName }}-cm
  namespace: {{ .Values.namespace }}
data:  
  metadata.yaml: |
    version: 2
    tables:
    - table:
        schema: public
        name: ixp_server_data
 
  