---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.project }}-configmap
  namespace: {{ .Values.namespace }}
data: 
  HASURA_GRAPHQL_ENABLE_CONSOLE: "{{ .Values.pchClientParser.conf.hasura_graphql_enable_console }}"
  HASURA_GRAPHQL_DEV_MODE: "{{ .Values.pchClientParser.conf.hasura_graphql_dev_mode }}"
  HASURA_GRAPHQL_ENABLED_LOG_TYPES: {{ .Values.pchClientParser.conf.hasura_graphql_enabled_log_types }}
  HASURA_GRAPHQL_SERVER_PORT: "{{ .Values.pchClientParser.conf.hasura_graphql_server_port }}"
  HASURA_GRAPHQL_CORS_DOMAIN: "{{ .Values.pchClientParser.conf.hasura_graphql_cors_domain }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.project }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres_db_v1: {{ .Values.secrets.postgres_db }}
  postgres_user_v1: {{ .Values.secrets.postgres_user }}
  postgres_password_v1: {{ .Values.secrets.postgres_password }}
  hasura_graphql_database_url_v1: {{ .Values.secrets.hasura_graphql_database_url }}
  