---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: {{ .Values.project }}
    app: {{ .Values.postgresQL.appName }}
    env: {{ .Values.environment }}
  name:  {{ .Values.postgresQL.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.postgresQL.service.port }}
    protocol: TCP
    targetPort: http
  selector:
    project: {{ .Values.project }}
    app: {{ .Values.postgresQL.appName }}
    env: {{ .Values.environment }}
  type: {{ .Values.postgresQL.service.type }}